### ISSUE TITLE
App threw an error during load ReferenceError: document is not defined

### ISSUE THREAD

**Issue by marcelodelta** [brrd/electron-tabs#132]
An error occurs when trying to load Electron-Tabs into main.js

Could anyone help?

Grateful for the attention

main.js
const TabGroup= require('electron-tabs')

App threw an error during load
ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\Marcelo\project\node_modules\electron-tabs\index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (C:\Users\Marcelo\OneDrive\projetos\Royal\royal_web\royaldesk\main.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (C:\Users\Marcelo\project\node_modules\electron\dist\resources\default_app.asar\main.js:110:16)
    at Object.<anonymous> (C:\Users\Marcelo\project\node_modules\electron\dist\resources\default_app.asar\main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1140:10)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:197:3197)

**Comment by brrd** [comment]
I guess you are trying to run electron-tabs in the main process. It is supposed to be used in the renderer process. Please make sure you are following [the doc](https://github.com/brrd/electron-tabs#usage).

This issue may also be helpful: #3.

If you still need help after this, then please provide information about your OS and your node version.
